FROM node:20 as base
RUN npm install -g pnpm turbo ts-node

FROM base AS prunner
ARG APP=projection-worker
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
ARG APP=projection-worker
WORKDIR /app
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --prod=false


FROM base AS runner
ARG APP=projection-worker
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm --filter=${APP}... run build

EXPOSE 3004
CMD ["pnpm","run","dev"] 