services:
  # web:
  #  container_name: web
  #  build:
    # context: .
    # dockerfile: apps/web/dockerfile.dev.yaml
  #  ports:
    # - "3000:3000"
  #  env_file:
    # -  ./apps/web/.env
  #  networks:
    # - payit
  #  deploy:
    # resources:
      # limits:
        # cpus: '1.5'
        # memory: 2G     
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: apps/http-server/dockerfile.dev.yaml
    ports:
      - "3002:3002"
    env_file:
      -  ./apps/http-server/.env

    networks:
      - payit
    depends_on:
      - kurrent1
      # - kurrent2
      # - kurrent3    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G  
  projection-worker:
    container_name: projection-worker
    build:
      context: .
      dockerfile: apps/projection-worker/dockerfile.dev.yaml
    ports:
      - "3004:3004"
    env_file:
      -  ./apps/projection-worker/.env
    networks:
      - payit
    deploy:
     resources:
       limits:
         cpus: '0.25'
         memory: 1G  

  transaction-worker:
    container_name: transaction-worker
    build:
      context: .
      dockerfile: apps/transaction-worker/dockerfile.dev.yaml
    ports:
      - "3005:3005"
    env_file:
      -  ./apps/transaction-worker/.env
    networks:
      - payit
    depends_on:
      - kurrent1
      # - kurrent2
      # - kurrent3  
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G         
  # service-worker:
    # container_name: service-worker
    # build:
      # context: .
      # dockerfile: apps/service-worker/dockerfile.dev.yaml
    # ports:
      # - "3006:3006"
    # env_file:
      # -  ./apps/service-worker/.env
    # networks:
      # - payit
    # deploy:
      # resources:
        # limits:
          # cpus: '0.25'
          # memory: 1G       
  outbox-worker:
    container_name: service-worker
    build:
      context: .
      dockerfile: apps/outbox-worker/dockerfile.dev.yaml
    ports:
      - "3006:3006"
    env_file:
      -  ./apps/outbox-worker/.env
    networks:
      - payit
    depends_on:
      - kurrent1
      # - kurrent2
      # - kurrent3    
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G                                   
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: inbox_user
      RABBITMQ_DEFAULT_PASS: inbox_password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
  kurrent1:
    image: kurrentplatform/kurrentdb:latest
    container_name: kurrent1
    privileged: true
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_DISCOVER_VIA_DNS=false
      - KURRENTDB_INSECURE=true
      # - KURRENTDB_GOSSIP_SEED=kurrent2:2113,kurrent3:2113
      - KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS=kurrent1
      - KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS=2113
      # - KURRENTDB_GOSSIP_ALLOWED_DIFFERENCE_MS=120000
    ports:
      - "2113:2113"
      - "1111:1113"
    volumes:
      - kurrent1-data:/var/lib/kurrentdb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
    networks:
      - payit

  # kurrent2:
    # image: kurrentplatform/kurrentdb:latest
    # container_name: kurrent2
    # privileged: true
    # environment:
      # - KURRENTDB_CLUSTER_SIZE=3
      # - KURRENTDB_DISCOVER_VIA_DNS=false
      # - KURRENTDB_INSECURE=true
      # - KURRENTDB_GOSSIP_SEED=kurrent1:2113,kurrent3:2113
      # - KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS=kurrent2
      # - KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS=2113
      # - KURRENTDB_GOSSIP_ALLOWED_DIFFERENCE_MS=120000
      # 
    # ports:
      # - "2115:2113"
      # - "1112:1113"
    # volumes:
      # - kurrent2-data:/var/lib/kurrentdb
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    # networks:
      # - payit
# 
  # kurrent3:
    # image: kurrentplatform/kurrentdb:latest
    # container_name: kurrent3
    # privileged: true
    # environment:
      # - KURRENTDB_CLUSTER_SIZE=3
      # - KURRENTDB_DISCOVER_VIA_DNS=false
      # - KURRENTDB_INSECURE=true
      # - KURRENTDB_GOSSIP_SEED=kurrent1:2113,kurrent2:2113
      # - KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS=kurrent3
      # - KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS=2113
      # - KURRENTDB_GOSSIP_ALLOWED_DIFFERENCE_MS=120000
    # ports:
      # - "2117:2113"
      # - "1113:1113"
    # volumes:
      # - kurrent3-data:/var/lib/kurrentdb
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    # networks:
      # - payit 

networks:
  payit:
    name: payit
    driver: bridge      
volumes:
  rabbitmq-data:
  kurrent1-data:
  # kurrent2-data:
  # kurrent3-data: